# Generated by Django 3.2.15 on 2022-10-07 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('bus', 'price')},
        ),
    ]
