# Generated by Django 3.2.15 on 2022-10-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0003_auto_20221010_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('booked', 'booked'), ('cancel', 'cancel')], default='apply', max_length=20),
        ),
    ]
