# Generated by Django 3.2.15 on 2022-10-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0004_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('booked', 'booked'), ('cancel', 'cancel')], default='booked', max_length=20),
        ),
    ]
