# Generated by Django 3.2.15 on 2022-10-13 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0005_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='buslist',
            unique_together={('bus_no', 'bus_name')},
        ),
    ]
