# Generated by Django 3.2.15 on 2022-10-20 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0007_alter_reservation_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('bus', 'user')},
        ),
    ]
