# Generated by Django 3.2.15 on 2022-10-25 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0009_auto_20221021_0654'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('bus', 'user', 'status')},
        ),
    ]
