# Generated by Django 3.2.15 on 2022-10-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0010_alter_reservation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('bus', 'user')},
        ),
    ]
