# Generated by Django 3.2.15 on 2022-11-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demofile', '0003_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(default=23),
            preserve_default=False,
        ),
    ]
