# Generated by Django 3.2.15 on 2022-11-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demofile', '0004_employee_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='j_date',
            field=models.DateField(null=True),
        ),
    ]
