# Generated by Django 3.2.15 on 2022-11-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demofile', '0005_employee_j_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='experience',
            field=models.PositiveBigIntegerField(default=4),
            preserve_default=False,
        ),
    ]
